feat: 支持为数据库表添加前缀/后缀
WeBankFinTech/WeBASE-Codegen-Monkey pull request #21
Opened 2020-06-16 12:10 UTC by huahuayu

1. 修改application.properties，增加以下配置项
system.tablePrefix - 表前缀
system.tablePostfix -  表后缀

2. monkey项目从application.properties读取配置动态生成和智能合约相关的表

3. 修改generate_bee.sh脚本，通过读config/resources/application.properties中的前后缀参数，拉取bee项目后使用sed替换表名再编译项目，达到动态更新表名的目的

4. install_scripts.tar.gz重新打包

2020-06-16 12:19 UTC, dalaocu commented on src/main/install_scripts/config/resources/application.properties
> +#system.tablePostfix=_1
这里最好默认为空，保持原有的格式。

2020-06-16 12:23 UTC, dalaocu requested changes
非常棒！
就是默认的表名配置还是兼容原有的规则，不要加_1的前缀。烦请修改后重新提交。

2020-06-16 12:39 UTC, huahuayu commented on src/main/install_scripts/config/resources/application.properties
> +#system.tablePostfix=_1
好的，已改

2020-06-17 03:50 UTC, dalaocu approved these changes

2020-06-17 03:50 UTC, merged